from .folder_search import (
    NODE_CLASS_MAPPINGS as FOLDER_SEARCH_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FOLDER_SEARCH_DISPLAY_NAME_MAPPINGS,
)
from .image_expand_with_fill import (
    NODE_CLASS_MAPPINGS as IMAGE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY_NAME_MAPPINGS,
)

from .video_prompt_viewer import (
    NODE_CLASS_MAPPINGS as VIDEO_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY_NAME_MAPPINGS,
)

from .video_prompt_save import (
    NODE_CLASS_MAPPINGS as SAVE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAVE_DISPLAY_NAME_MAPPINGS,
)

from . import waveform

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {
    **SAVE_CLASS_MAPPINGS,
    **VIDEO_CLASS_MAPPINGS,
    **IMAGE_CLASS_MAPPINGS,
    **FOLDER_SEARCH_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SAVE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_DISPLAY_NAME_MAPPINGS,
    **IMAGE_DISPLAY_NAME_MAPPINGS,
    **FOLDER_SEARCH_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
