from .folder_search import (
    NODE_CLASS_MAPPINGS as FOLDER_SEARCH_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FOLDER_SEARCH_DISPLAY_NAME_MAPPINGS,
)
from .image_expand_with_fill import (
    NODE_CLASS_MAPPINGS as IMAGE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_DISPLAY_NAME_MAPPINGS,
)

from .video_prompt_viewer import (
    NODE_CLASS_MAPPINGS as VIDEO_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_DISPLAY_NAME_MAPPINGS,
)

from .video_prompt_save import (
    NODE_CLASS_MAPPINGS as SAVE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SAVE_DISPLAY_NAME_MAPPINGS,
)

from .media_bank import (
    NODE_CLASS_MAPPINGS as MEDIA_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MEDIA_DISPLAY_NAME_MAPPINGS,
)

from .seed_slots import (
    NODE_CLASS_MAPPINGS as SEED_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEED_DISPLAY_NAME_MAPPINGS,
)

from .prompt_tools import (
    NODE_CLASS_MAPPINGS as PROMPT_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PROMPT_DISPLAY_NAME_MAPPINGS,
)

from .video_compare import (
    NODE_CLASS_MAPPINGS as COMPARE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMPARE_DISPLAY_NAME_MAPPINGS,
)

from . import waveform

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {
    **COMPARE_CLASS_MAPPINGS,
    **PROMPT_CLASS_MAPPINGS,
    **SEED_CLASS_MAPPINGS,
    **MEDIA_CLASS_MAPPINGS,
    **SAVE_CLASS_MAPPINGS,
    **VIDEO_CLASS_MAPPINGS,
    **IMAGE_CLASS_MAPPINGS,
    **FOLDER_SEARCH_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **COMPARE_DISPLAY_NAME_MAPPINGS,
    **PROMPT_DISPLAY_NAME_MAPPINGS,
    **SEED_DISPLAY_NAME_MAPPINGS,
    **MEDIA_DISPLAY_NAME_MAPPINGS,
    **SAVE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_DISPLAY_NAME_MAPPINGS,
    **IMAGE_DISPLAY_NAME_MAPPINGS,
    **FOLDER_SEARCH_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
